#!/usr/bin/env python
"""
ctopy -- a quick and dirty C-to-Python translator

FIXME: The curses mapping is quite incomplete.

Libraries not mapped that theoretically could be: curses.panel, dbm,
md5, popen2, pty, resource, sha, subprocess, syslog, time.  Some of these
would need more elaborate machinery for method translation.

Python library bindings are as of 2.6a0.
"""
import sys, re

stringify = []

printflike = ["printf", "sprintf", "vfprintf"]

shorthands = {
    'id' : r"[a-zA-Z_][a-zA-Z0-9._]*",
    'exp' : r"[a-zA-Z0-9._\-+\*/]+",
    'type' : r"\bvoid\b|\bint\b|\bbool\b|\bchar\b|\bshort\b|\bdouble\b|\blong\b|\bfloat\b|\btime_t\b|\bFILE\b|bWINDOW\b",
    'class' : r"\b__dummyclass__\b",
    'ind' : r"(\n[ \t]*)",		# Whitespace at start of line
    'eol' : r"[ \t]*(?=\n|\Z)",		# Whitespace to end of line or comment
    'arg' : r"([^,]+),\s*",		# initial or medial argument
    'farg' : r"([^)]+)",			# final argument
}

# C functions and constants to be mapped into Python standard library bindings.
funmappings = (
    # File object methods (from C stdlib).
    (r"\bfclose\(%(farg)s\)", r"\1.close()", None),
    (r"\bfflush\(%(farg)s\)", r"\1.flush()", None),
    (r"\bfileno\(%(farg)s\)", r"\1.fileno()", None),
    (r"\bfprintf\(%(arg)s\)", r"\1.write()", None),
    (r"\bfseek\(%(arg)s", r"\1.seek(", None),
    (r"\bftell\(%(farg)s\)", r"\1.tell()", None),
    (r"\bftruncate\(%(arg)s", r"\1.truncate(", None),
    # Python atexit library
    (r"\batexit\(", r"atexit.register(", "atexit"),
    # Python crypt library
    (r"\bcrypt\(", r"crypt.crypt(", "crypt"),
    # Curses library.  Below are all function calls listed in the
    # ncurses(3) version 5.5 manual page in the order they are listed.
    # The ones we don't translate have been left in as comments,
    # pending future improvements.  The largest category of things not
    # translated is the wide-character support; it's possible there's
    # an easy way to map this, but I don't have a need for it.
    # Mappings marked "EXCEPTION" violate the convention that the C names
    # of window methods begin with 'w'. Mappings marked "NONTRIVIAL"
    # map a C entry point into a Python entry point with a different name,
    # usually toi throw away a length argument Python doesn't need.
    (r"\bCOLOR_PAIR\(", "curses.color_pair(", "curses"),
    (r"\bPAIR_NUMBER\(", "curses.pair_number(", "curses"),
    #_nc_tracebits           curs_trace(3X)*
    #_traceattr              curs_trace(3X)*
    #_traceattr2             curs_trace(3X)*
    #_tracechar              curs_trace(3X)*
    #_tracechtype            curs_trace(3X)*
    #_tracechtype2           curs_trace(3X)*
    #_tracedump              curs_trace(3X)*
    #_tracef                 curs_trace(3X)*
    #_tracemouse             curs_trace(3X)*
    #add_wch                 curs_add_wch(3X)
    #add_wchnstr             curs_add_wchstr(3X)
    #add_wchstr              curs_add_wchstr(3X)
    (r"\baddch\(", r"stdscr.addch(", "curses"),
    #addchnstr               curs_addchstr(3X)
    #addchstr                curs_addchstr(3X)
    (r"\baddnstr(", r"stdscr.addnstr(", "curses"),
    #addnwstr                curs_addwstr(3X)
    (r"\baddstr\(", r"stdscr.addstr(", "curses"),
    #addwstr                 curs_addwstr(3X)
    #assume_default_colors   default_colors(3X)*
    #attr_get                curs_attr(3X)
    (r"\battr_off\(", r"stdscr.attrof(", r"curses"),
    (r"\battr_on\(", r"stdscr.attron(", r"curses"),
    (r"\battr_set\(", r"stdscr.attrset(", r"curses"),
    (r"\battroff\(", r"stdscr.attrof(", r"curses"),
    (r"\battron\(", r"stdscr.attron(", r"curses"),
    (r"\battrset\(", r"stdscr.attrset(", r"curses"),
    (r"\bbaudrate\(", r"curses.baudrate(", r"curses"),
    (r"\bbeep\(", r"curses.beep(", r"curses"),
    (r"\bbkgd\(", r"stdscr.bkgd(", r"curses"),
    (r"\bbkgdset\(", r"stsdcr.bkgdset(", r"curses"),
    #bkgrnd                  curs_bkgrnd(3X)
    #bkgrndset               curs_bkgrnd(3X)
    (r"\bborder\(", r"stdscr.border(", r"curses"), 
    #border_set              curs_border_set(3X)
    (r"\bbox\(%(arg)s", r"\1.box(", r"curses"),		# EXCEPTION
    #box_set                 curs_border_set(3X)
    (r"\bcan_change_color\(", r"curses.can_change_color(", r"curses"),
    (r"\bcbreak\(", r"curses.cbreak(", r"curses"),
    #chgat                   curs_attr(3X)
    (r"\bclear\(", r"stdscr.clear(", r"curses"),
    (r"\bclearok\(", r"stdscr.clearok(", r"curses"),
    (r"\bclrtobot\(", r"stdscr.clrtobot(", r"curses"),
    (r"\bclrtoeol\(", r"stdscr.clrtoeol(", r"curses"),
    (r"\bcolor_content\(", r"curses.color_content(", r"curses"),
    #color_set               curs_attr(3X)
    #copywin                 curs_overlay(3X)
    (r"\bcurs_set\(", r"curses.curs_set(", r"curses"),
    #curses_version          curs_extend(3X)*
    (r"\bdef_prog_mode\(", r"curses.def_prog_mode(", r"curses"),
    (r"\bdef_shell_mode\(", r"curses.def_shell_mode(", r"curses"),
    #define_key              define_key(3X)*
    #del_curterm             curs_terminfo(3X)
    (r"\bdelay_output\(", r"curses.delay_output(", r"curses"),
    (r"\bdelch\(", r"stdscr.delch(", r"curses"),
    (r"\bdeleteln\(", r"stdscr.deleteln(", r"curses"),
    #delscreen               curs_initscr(3X)
    #delwin                  curs_window(3X)
    (r"\bderwin\(%(arg)s", r"\1.derwin(", "curses"),		# EXCEPTION
    (r"\bdoupdate\(\)", r"curses.doupdate()", "curses"),
    #dupwin                  curs_window(3X)
    (r"\becho\(", r"curses.echo(", "curses"),
    #echo_wchar              curs_add_wch(3X)
    (r"\bechochar\(", r"stdscr.echochar(", "curses"),
    (r"\bendwin\(", r"curses.endwin(", "curses"),
    (r"\berase\(", r"stdscr.erase(", "curses"),
    #erasechar               curs_termattrs(3X)
    #erasewchar              curs_termattrs(3X)
    (r"\bfilter\(\)", r"curses.filter()", "curses"),
    (r"\bflash\(\)", r"curses.flash()", "curses"),
    (r"\bflushinp\(\)", r"curses.flushinp()", "curses"),
    #get_wch                 curs_get_wch(3X)
    #get_wstr                curs_get_wstr(3X)
    (r"\bgetbegyx\(%(arg)s%(arg)s%(farg)s\)",		# EXCEPTION
     r"(\2, \3) = \1.getbegyx()", "curses"),
    (r"\bgetbkgd\(", r"\1.getbkgd(", "curses"),		# EXCEPTION
    #getbkgrnd               curs_bkgrnd(3X)
    #getcchar                curs_getcchar(3X)
    (r"\bgetch\(", r"stdscr.getch(", "curses"),
    (r"\bgetmaxyx\(%(arg)s", r"\1.getmaxyx(", "curses"),	# EXCEPTION
    (r"\bgetmouse\(%(farg)s\)", r"\1 = curses.getmouse()", "curses"),
    #getn_wstr               curs_get_wstr(3X)
    (r"\bgetnstr\(%(arg)s%(farg)s\)",	# NONTRIVIAL
     r"\1 = stdscr.getstr(\2)", "curses"),
    (r"\bgetparyx\(%(arg)s%(arg)s%(farg)s\)",	# EXCEPTION
     r"(\2, \3) = \1.getparyx()", "curses"),
    (r"\bgetsyx\(%(arg)s%(farg)s\)", r"(\1, \2) = curses.getsyx()", "curses"),
    (r"\bgetstr\(\)", r"stdscr.getstr()", "curses"),
    (r"\bgetyx\(%(arg)s%(arg)s%(farg)s\)",		#EXCEPTION
     r"(\2, \3) = \1.getyx()", "curses"),
    (r"\bgetwin\(", r"curses.getwin(", "curses"),
    (r"\bhalfdelay\(", r"curses.halfdelay(", "curses"),
    (r"\bhas_colors\(", r"curses.has_colors(", "curses"),
    (r"\bhas_ic\(", r"curses.has_ic(", "curses"),
    (r"\bhas_il\(", r"curses.has_il(", "curses"),
    (r"\bhas_key\(", r"curses.has_key(", "curses"),
    (r"\bhline\(", r"stdscr.hline(", "curses"),
    #hline_set               curs_border_set(3X)
    (r"\bidcok\(%(arg)s", r"\1.idcok(", "curses"),	# EXCEPTION
    (r"\bidlok\(%(arg)s", r"\1.idlok(", "curses"),	# EXCEPTION
    (r"\bimmedok\(%(arg)s", r"\1.immedok(", "curses"),	# EXCEPTION
    # in_wch                  curs_in_wch(3X)
    # in_wchnstr              curs_in_wchstr(3X)
    # in_wchstr               curs_in_wchstr(3X)
    (r"\binch\(", r"stdscr.inch(", "curses"),
    #inchnstr                curs_inchstr(3X)
    #inchstr                 curs_inchstr(3X)
    (r"\binit_color\(", r"curses.init_color(", "curses"),
    (r"\binit_pair\(", r"curses.init_pair(", "curses"),
    (r"\binitscr\(", r"curses.initscr(", "curses"),
    (r"\binnstr\(%(arg)s", r"\1.instr(", "curses"),	# NONTRIVIAL
    #innwstr                 curs_inwstr(3X)
    #ins_nwstr               curs_ins_wstr(3X)
    #ins_wch                 curs_ins_wch(3X)
    #ins_wstr                curs_ins_wstr(3X)
    #                 insch                   curs_insch(3X)
    #                 insdelln                curs_deleteln(3X)
    #                 insertln                curs_deleteln(3X)
    #                 insnstr                 curs_insstr(3X)
    #                 insstr                  curs_insstr(3X)
    #                 instr                   curs_instr(3X)
    #                 intrflush               curs_inopts(3X)
    #                 inwstr                  curs_inwstr(3X)
    #                 is_linetouched          curs_touch(3X)
    #                 is_wintouched           curs_touch(3X)
    #                 isendwin                curs_initscr(3X)
    #                 key_defined             key_defined(3X)*
    #                 key_name                curs_util(3X)
    #                 keybound                keybound(3X)*
    #                 keyname                 curs_util(3X)
    #                 keyok                   keyok(3X)*
    #                 keypad                  curs_inopts(3X)
    #                 killchar                curs_termattrs(3X)
    #                 killwchar               curs_termattrs(3X)
    #                 leaveok                 curs_outopts(3X)
    #                 longname                curs_termattrs(3X)
    #                 mcprint                 curs_print(3X)*
    #                 meta                    curs_inopts(3X)
    #                 mouse_trafo             curs_mouse(3X)*
    #                 mouseinterval           curs_mouse(3X)*
    #                 mousemask               curs_mouse(3X)*
    #                 move                    curs_move(3X)
    #                 mvadd_wch               curs_add_wch(3X)
    #                 mvadd_wchnstr           curs_add_wchstr(3X)
    #                 mvadd_wchstr            curs_add_wchstr(3X)
    #                 mvaddch                 curs_addch(3X)
    #                 mvaddchnstr             curs_addchstr(3X)
    #                 mvaddchstr              curs_addchstr(3X)
    #                 mvaddnstr               curs_addstr(3X)
    #                 mvaddnwstr              curs_addwstr(3X)
    #                 mvaddstr                curs_addstr(3X)
    #                 mvaddwstr               curs_addwstr(3X)
    #                 mvchgat                 curs_attr(3X)
    #                 mvcur                   curs_terminfo(3X)
    #                 mvdelch                 curs_delch(3X)
    #                 mvderwin                curs_window(3X)
    #                 mvget_wch               curs_get_wch(3X)
    #                 mvget_wstr              curs_get_wstr(3X)
    #                 mvgetch                 curs_getch(3X)
    #                 mvgetn_wstr             curs_get_wstr(3X)
    #                 mvgetnstr               curs_getstr(3X)
    #                 mvgetstr                curs_getstr(3X)
    #                 mvhline                 curs_border(3X)
    #                 mvhline_set             curs_border_set(3X)
    #                 mvin_wch                curs_in_wch(3X)
    #                 mvin_wchnstr            curs_in_wchstr(3X)
    #                 mvin_wchstr             curs_in_wchstr(3X)
    #                 mvinch                  curs_inch(3X)
    #                 mvinchnstr              curs_inchstr(3X)
    #                 mvinchstr               curs_inchstr(3X)
    #                 mvinnstr                curs_instr(3X)
    #                 mvinnwstr               curs_inwstr(3X)
    #                 mvins_nwstr             curs_ins_wstr(3X)
    #                 mvins_wch               curs_ins_wch(3X)
    #                 mvins_wstr              curs_ins_wstr(3X)
    #                 mvinsch                 curs_insch(3X)
    #                 mvinsnstr               curs_insstr(3X)
    #                 mvinsstr                curs_insstr(3X)
    #                 mvinstr                 curs_instr(3X)
    #                 mvinwstr                curs_inwstr(3X)
    #                 mvprintw                curs_printw(3X)
    #                 mvscanw                 curs_scanw(3X)
    #                 mvvline                 curs_border(3X)
    #                 mvvline_set             curs_border_set(3X)
    #                 mvwadd_wch              curs_add_wch(3X)
    #                 mvwadd_wchnstr          curs_add_wchstr(3X)
    #                 mvwadd_wchstr           curs_add_wchstr(3X)
    #                 mvwaddch                curs_addch(3X)
    #                 mvwaddchnstr            curs_addchstr(3X)
    #                 mvwaddchstr             curs_addchstr(3X)
    #                 mvwaddnstr              curs_addstr(3X)
    #                 mvwaddnwstr             curs_addwstr(3X)
    #                 mvwaddstr               curs_addstr(3X)
    #                 mvwaddwstr              curs_addwstr(3X)
    #                 mvwchgat                curs_attr(3X)
    #                 mvwdelch                curs_delch(3X)
    #                 mvwget_wch              curs_get_wch(3X)
    #                 mvwget_wstr             curs_get_wstr(3X)
    #                 mvwgetch                curs_getch(3X)
    #                 mvwgetn_wstr            curs_get_wstr(3X)
    #                 mvwgetnstr              curs_getstr(3X)
    #                 mvwgetstr               curs_getstr(3X)
    #                 mvwhline                curs_border(3X)
    #                 mvwhline_set            curs_border_set(3X)
    #                 mvwin                   curs_window(3X)
    #                 mvwin_wch               curs_in_wch(3X)
    #                 mvwin_wchnstr           curs_in_wchstr(3X)
    #                 mvwin_wchstr            curs_in_wchstr(3X)
    #                 mvwinch                 curs_inch(3X)
    #                 mvwinchnstr             curs_inchstr(3X)
    #                 mvwinchstr              curs_inchstr(3X)
    #                 mvwinnstr               curs_instr(3X)
    #                 mvwinnwstr              curs_inwstr(3X)
    #                 mvwins_nwstr            curs_ins_wstr(3X)
    #                 mvwins_wch              curs_ins_wch(3X)
    #                 mvwins_wstr             curs_ins_wstr(3X)
    #                 mvwinsch                curs_insch(3X)
    #                 mvwinsnstr              curs_insstr(3X)
    #                 mvwinsstr               curs_insstr(3X)
    #                 mvwinstr                curs_instr(3X)
    #                 mvwinwstr               curs_inwstr(3X)
    #                 mvwprintw               curs_printw(3X)
    #                 mvwscanw                curs_scanw(3X)
    #                 mvwvline                curs_border(3X)
    #                 mvwvline_set            curs_border_set(3X)
    #                 napms                   curs_kernel(3X)
    #                 newpad                  curs_pad(3X)
    #                 newterm                 curs_initscr(3X)
    #                 newwin                  curs_window(3X)
    #                 nl                      curs_outopts(3X)
    #                 nocbreak                curs_inopts(3X)
    #                 nodelay                 curs_inopts(3X)
    #                 noecho                  curs_inopts(3X)
    #                 nonl                    curs_outopts(3X)
    #                 noqiflush               curs_inopts(3X)
    #                 noraw                   curs_inopts(3X)
    #                 notimeout               curs_inopts(3X)
    #                 overlay                 curs_overlay(3X)
    #                 overwrite               curs_overlay(3X)
    #                 pair_content            curs_color(3X)
    #                 pechochar               curs_pad(3X)
    #                 pnoutrefresh            curs_pad(3X)
    #                 prefresh                curs_pad(3X)
    #                 printw                  curs_printw(3X)
    #                 putp                    curs_terminfo(3X)
    #                 putwin                  curs_util(3X)
    #                 qiflush                 curs_inopts(3X)
    #                 raw                     curs_inopts(3X)
    #                 redrawwin               curs_refresh(3X)
    #                 refresh                 curs_refresh(3X)
    #                 reset_prog_mode         curs_kernel(3X)
    #                 reset_shell_mode        curs_kernel(3X)
    #                 resetty                 curs_kernel(3X)
    #                 resizeterm              resizeterm(3X)*
    #                 restartterm             curs_terminfo(3X)
    #                 ripoffline              curs_kernel(3X)
    #                 savetty                 curs_kernel(3X)
    #                 scanw                   curs_scanw(3X)
    #                 scr_dump                curs_scr_dump(3X)
    #                 scr_init                curs_scr_dump(3X)
    #                 scr_restore             curs_scr_dump(3X)
    #                 scr_set                 curs_scr_dump(3X)
    #                 scrl                    curs_scroll(3X)
    #                 scroll                  curs_scroll(3X)
    #                 scrollok                curs_outopts(3X)
    #                 set_curterm             curs_terminfo(3X)
    #                 set_term                curs_initscr(3X)
    #                 setcchar                curs_getcchar(3X)
    #                 setscrreg               curs_outopts(3X)
    #                 setsyx                  curs_kernel(3X)
    #                 setterm                 curs_terminfo(3X)
    #                 setupterm               curs_terminfo(3X)
    #                 slk_attr                curs_slk(3X)*
    #                 slk_attr_off            curs_slk(3X)
    #                 slk_attr_on             curs_slk(3X)
    #                 slk_attr_set            curs_slk(3X)
    #                 slk_attroff             curs_slk(3X)
    #                 slk_attron              curs_slk(3X)
    #                 slk_attrset             curs_slk(3X)
    #                 slk_clear               curs_slk(3X)
    #                 slk_color               curs_slk(3X)
    #                 slk_init                curs_slk(3X)
    #                 slk_label               curs_slk(3X)
    #                 slk_noutrefresh         curs_slk(3X)
    #                 slk_refresh             curs_slk(3X)
    #                 slk_restore             curs_slk(3X)
    #                 slk_set                 curs_slk(3X)
    #                 slk_touch               curs_slk(3X)
    #                 standend                curs_attr(3X)
    #                 standout                curs_attr(3X)
    #                 start_color             curs_color(3X)
    #                 subpad                  curs_pad(3X)
    #                 subwin                  curs_window(3X)
    #                 syncok                  curs_window(3X)
    #                 term_attrs              curs_termattrs(3X)
    #                 termattrs               curs_termattrs(3X)
    #                 termname                curs_termattrs(3X)
    #                 tgetent                 curs_termcap(3X)
    #                 tgetflag                curs_termcap(3X)
    #                 tgetnum                 curs_termcap(3X)
    #                 tgetstr                 curs_termcap(3X)
    #                 tgoto                   curs_termcap(3X)
    #                 tigetflag               curs_terminfo(3X)
    #                 tigetnum                curs_terminfo(3X)
    #                 tigetstr                curs_terminfo(3X)
    #                 timeout                 curs_inopts(3X)
    #                 touchline               curs_touch(3X)
    #                 touchwin                curs_touch(3X)
    #                 tparm                   curs_terminfo(3X)
    #                 tputs                   curs_termcap(3X)
    #                 tputs                   curs_terminfo(3X)
    #                 trace                   curs_trace(3X)*
    #                 typeahead               curs_inopts(3X)
    #                 unctrl                  curs_util(3X)
    #                 unget_wch               curs_get_wch(3X)
    #                 ungetch                 curs_getch(3X)
    #                 ungetmouse              curs_mouse(3X)*
    #                 untouchwin              curs_touch(3X)
    #                 use_default_colors      default_colors(3X)*
    #                 use_env                 curs_util(3X)
    #                 use_extended_names      curs_extend(3X)*
    #                 vid_attr                curs_terminfo(3X)
    #                 vid_puts                curs_terminfo(3X)
    #                 vidattr                 curs_terminfo(3X)
    #                 vidputs                 curs_terminfo(3X)
    #                 vline                   curs_border(3X)
    #                 vline_set               curs_border_set(3X)
    #                 vw_printw               curs_printw(3X)
    #                 vw_scanw                curs_scanw(3X)
    #                 vwprintw                curs_printw(3X)
    #                 vwscanw                 curs_scanw(3X)
    #                 wadd_wch                curs_add_wch(3X)
    #                 wadd_wchnstr            curs_add_wchstr(3X)
    #                 wadd_wchstr             curs_add_wchstr(3X)
    #                 waddch                  curs_addch(3X)
    #                 waddchnstr              curs_addchstr(3X)
    #                 waddchstr               curs_addchstr(3X)
    #                 waddnstr                curs_addstr(3X)
    #                 waddnwstr               curs_addwstr(3X)
    #                 waddstr                 curs_addstr(3X)
    #                 waddwstr                curs_addwstr(3X)
    #                 wattr_get               curs_attr(3X)
    #                 wattr_off               curs_attr(3X)
    #                 wattr_on                curs_attr(3X)
    #                 wattr_set               curs_attr(3X)
    #                 wattroff                curs_attr(3X)
    #                 wattron                 curs_attr(3X)
    #                 wattrset                curs_attr(3X)
    #                 wbkgd                   curs_bkgd(3X)
    #                 wbkgdset                curs_bkgd(3X)
    #                 wbkgrnd                 curs_bkgrnd(3X)
    #                 wbkgrndset              curs_bkgrnd(3X)
    #                 wborder                 curs_border(3X)
    #                 wborder_set             curs_border_set(3X)
    #                 wchgat                  curs_attr(3X)
    #                 wclear                  curs_clear(3X)
    #                 wclrtobot               curs_clear(3X)
    #                 wclrtoeol               curs_clear(3X)
    #                 wcolor_set              curs_attr(3X)
    #                 wcursyncup              curs_window(3X)
    #                 wdelch                  curs_delch(3X)
    #                 wdeleteln               curs_deleteln(3X)
    #                 wecho_wchar             curs_add_wch(3X)
    #                 wechochar               curs_addch(3X)
    #                 wenclose                curs_mouse(3X)*
    #                 werase                  curs_clear(3X)
    #                 wget_wch                curs_get_wch(3X)
    #                 wget_wstr               curs_get_wstr(3X)
    #                 wgetbkgrnd              curs_bkgrnd(3X)
    #                 wgetch                  curs_getch(3X)
    #                 wgetn_wstr              curs_get_wstr(3X)
    #                 wgetnstr                curs_getstr(3X)
    #                 wgetstr                 curs_getstr(3X)
    #                 whline                  curs_border(3X)
    #                 whline_set              curs_border_set(3X)
    #                 win_wch                 curs_in_wch(3X)
    #                 win_wchnstr             curs_in_wchstr(3X)
    #                 win_wchstr              curs_in_wchstr(3X)
    #                 winch                   curs_inch(3X)
    #                 winchnstr               curs_inchstr(3X)
    #                 winchstr                curs_inchstr(3X)
    #                 winnstr                 curs_instr(3X)
    #                 winnwstr                curs_inwstr(3X)
    #                 wins_nwstr              curs_ins_wstr(3X)
    #                 wins_wch                curs_ins_wch(3X)
    #                 wins_wstr               curs_ins_wstr(3X)
    #                 winsch                  curs_insch(3X)
    #                 winsdelln               curs_deleteln(3X)
    #                 winsertln               curs_deleteln(3X)
    #                 winsnstr                curs_insstr(3X)
    #                 winsstr                 curs_insstr(3X)
    #                 winstr                  curs_instr(3X)
    #                 winwstr                 curs_inwstr(3X)
    #                 wmouse_trafo            curs_mouse(3X)*
    #                 wmove                   curs_move(3X)
    #                 wnoutrefresh            curs_refresh(3X)
    #                 wprintw                 curs_printw(3X)
    #                 wredrawln               curs_refresh(3X)
    #                 wrefresh                curs_refresh(3X)
    #                 wresize                 wresize(3X)*
    #                 wscanw                  curs_scanw(3X)
    #                 wscrl                   curs_scroll(3X)
    #                 wsetscrreg              curs_outopts(3X)
    #                 wstandend               curs_attr(3X)
    #                 wstandout               curs_attr(3X)
    #                 wsyncdown               curs_window(3X)
    #                 wsyncup                 curs_window(3X)
    #                 wtimeout                curs_inopts(3X)
    #                 wtouchln                curs_touch(3X)
    #                 wunctrl                 curs_util(3X)
    #                 wvline                  curs_border(3X)
    #                 wvline_set              curs_border_set(3X)
    # And this does the curses library constants
    (r"\bA_ATTRIBUTES\b", r"curses.A_ATTRIBUTES"),
    (r"\bA_NORMAL\b", r"curses.A_NORMAL"),
    (r"\bA_STANDOUT\b", r"curses.A_STANDOUT"),
    (r"\bA_UNDERLINE\b", r"curses.A_UNDERLINE"),
    (r"\bA_REVERSE\b", r"curses.A_REVERSE"),
    (r"\bA_BLINK\b", r"curses.A_BLINK"),
    (r"\bA_DIM\b", r"curses.A_DIM"),
    (r"\bA_BOLDW\b", r"curses.A_BOLDW"),
    (r"\bA_ALTCHARSET\b", r"curses.A_ALTCHARSET"),
    (r"\bA_INVIS\b", r"curses.A_INVIS"),
    (r"\bA_PROTECT\b", r"curses.A_PROTECT"),
    (r"\bA_HORIZONTAL\b", r"curses.A_HORIZONTAL"),
    (r"\bA_LEFT\b", r"curses.A_LEFT"),
    (r"\bA_LOW\b", r"curses.A_LOW"),
    (r"\bA_RIGHT\b", r"curses.A_RIGHT"),
    (r"\bA_TOP\b", r"curses.A_TOP"),
    (r"\bA_VERTICAL\b", r"curses.A_VERTICAL"),
    (r"\bOLOR_BLACK\b", r"curses.OLOR_BLACK"),
    (r"\bOLOR_RED\b", r"curses.OLOR_RED"),
    (r"\bOLOR_GREEN\b", r"curses.OLOR_GREEN"),
    (r"\bOLOR_YELLOW\b", r"curses.OLOR_YELLOW"),
    (r"\bOLOR_BLUE\b", r"curses.OLOR_BLUE"),
    (r"\bOLOR_MAGENTA\b", r"curses.OLOR_MAGENTA"),
    (r"\bOLOR_CYAN\b", r"curses.OLOR_CYAN"),
    (r"\bOLOR_WHITE\b", r"curses.OLOR_WHITE"),
    (r"\bACS_ULCORNER\b", r"curses.ACS_ULCORNER"),
    (r"\bACS_LLCORNER\b", r"curses.ACS_LLCORNER"),
    (r"\bACS_URCORNER\b", r"curses.ACS_URCORNER"),
    (r"\bACS_LRCORNER\b", r"curses.ACS_LRCORNER"),
    (r"\bACS_LTEE\b", r"curses.ACS_LTEE"),
    (r"\bACS_RTEE\b", r"curses.ACS_RTEE"),
    (r"\bACS_BTEE\b", r"curses.ACS_BTEE"),
    (r"\bACS_TTEE\b", r"curses.ACS_TTEE"),
    (r"\bACS_HLINE\b", r"curses.ACS_HLINE"),
    (r"\bACS_VLINE\b", r"curses.ACS_VLINE"),
    (r"\bACS_PLUS\b", r"curses.ACS_PLUS"),
    (r"\bACS_S1\b", r"curses.ACS_S1"),
    (r"\bACS_S9\b", r"curses.ACS_S9"),
    (r"\bACS_DIAMOND\b", r"curses.ACS_DIAMOND"),
    (r"\bACS_CKBOARD\b", r"curses.ACS_CKBOARD"),
    (r"\bACS_DEGREE\b", r"curses.ACS_DEGREE"),
    (r"\bACS_PLMINUS\b", r"curses.ACS_PLMINUS"),
    (r"\bACS_BULLET\b", r"curses.ACS_BULLET"),
    (r"\bACS_LARROW\b", r"curses.ACS_LARROW"),
    (r"\bACS_RARROW\b", r"curses.ACS_RARROW"),
    (r"\bACS_DARROW\b", r"curses.ACS_DARROW"),
    (r"\bACS_UARROW\b", r"curses.ACS_UARROW"),
    (r"\bACS_BOARD\b", r"curses.ACS_BOARD"),
    (r"\bACS_LANTERN\b", r"curses.ACS_LANTERN"),
    (r"\bACS_BLOCK\b", r"curses.ACS_BLOCK"),
    (r"\bBUTTON(\d)_PRESSED\b", r"BUTTON\1_PRESSED"),
    (r"\bBUTTON(\d)_RELEASED\b", r"BUTTON\1_RELEASED"),
    (r"\bBUTTON(\d)_CLICKED\b", r"BUTTON\1_CLICKED"),
    (r"\bBUTTON(\d)_DOUBLE_CLICKED\b", r"BUTTON\1_DOUBLE_CLICKED"),
    (r"\bBUTTON(\d)_TRIPLE_CLICKED\b", r"BUTTON\1_TRIPLE_CLICKED"),
    (r"\bBUTTON_SHIFT\b", r"BUTTON_SHIFT"),
    (r"\bBUTTON_CTRL\b", r"BUTTON_CTRL"),
    (r"\bBUTTON_ALT\b", r"BUTTON_ALT"),
    (r"\bALL_MOUSE_EVENTS\b", r"ALL_MOUSE_EVENTS"),
    (r"\bREPORT_MOUSE_POSITION\b", r"REPORT_MOUSE_POSITION"),
    # Python curses.ascii library
    (r"\bisalnum\(", r"curses.ascii.isalnum("),
    (r"\bisalpha\(", r"curses.ascii.isalpha("),
    (r"\bisascii\(", r"curses.ascii.isascii("),
    (r"\bisblank\(", r"curses.ascii.isblank("),
    (r"\biscntrl\(", r"curses.ascii.iscntrl("),
    (r"\bisdigit\(", r"curses.ascii.isdigit("),
    (r"\bisgraph\(", r"curses.ascii.isgraph("),
    (r"\bislower\(", r"curses.ascii.islower("),
    (r"\bisprint\(", r"curses.ascii.isprint("),
    (r"\bispunct\(", r"curses.ascii.ispunct("),
    (r"\bisspace\(", r"curses.ascii.isspace("),
    (r"\bisupper\(", r"curses.ascii.isupper("),
    (r"\bisxdigit\(", r"curses.ascii.isxdigit("),
    (r"\bisctrl\(", r"curses.ascii.isctrl("),
    (r"\bismeta\(", r"curses.ascii.ismeta("),
    # Python errno library
    (r"\bEPERM\b", r"errno.EPERM"),
    (r"\bENOENT\b", r"errno.ENOENT"),
    (r"\bESRCH\b", r"errno.ESRCH"),
    (r"\bEINTR\b", r"errno.EINTR"),
    (r"\bEIO\b", r"errno.EIO"),
    (r"\bENXIO\b", r"errno.ENXIO"),
    (r"\bE2BIG\b", r"errno.E2BIG"),
    (r"\bENOEXEC\b", r"errno.ENOEXEC"),
    (r"\bEBADF\b", r"errno.EBADF"),
    (r"\bECHILD\b", r"errno.ECHILD"),
    (r"\bEAGAIN\b", r"errno.EAGAIN"),
    (r"\bENOMEM\b", r"errno.ENOMEM"),
    (r"\bEACCES\b", r"errno.EACCES"),
    (r"\bEFAULT\b", r"errno.EFAULT"),
    (r"\bENOTBLK\b", r"errno.ENOTBLK"),
    (r"\bEBUSY\b", r"errno.EBUSY"),
    (r"\bEEXIST\b", r"errno.EEXIST"),
    (r"\bEXDEV\b", r"errno.EXDEV"),
    (r"\bENODEV\b", r"errno.ENODEV"),
    (r"\bENOTDIR\b", r"errno.ENOTDIR"),
    (r"\bEISDIR\b", r"errno.EISDIR"),
    (r"\bEINVAL\b", r"errno.EINVAL"),
    (r"\bENFILE\b", r"errno.ENFILE"),
    (r"\bEMFILE\b", r"errno.EMFILE"),
    (r"\bENOTTY\b", r"errno.ENOTTY"),
    (r"\bETXTBSY\b", r"errno.ETXTBSY"),
    (r"\bEFBIG\b", r"errno.EFBIG"),
    (r"\bENOSPC\b", r"errno.ENOSPC"),
    (r"\bESPIPE\b", r"errno.ESPIPE"),
    (r"\bEROFS\b", r"errno.EROFS"),
    (r"\bEMLINK\b", r"errno.EMLINK"),
    (r"\bEPIPE\b", r"errno.EPIPE"),
    (r"\bEDOM\b", r"errno.EDOM"),
    (r"\bERANGE\b", r"errno.ERANGE"),
    (r"\bEDEADLK\b", r"errno.EDEADLK"),
    (r"\bENAMETOOLONG\b", r"errno.ENAMETOOLONG"),
    (r"\bENOLCK\b", r"errno.ENOLCK"),
    (r"\bENOSYS\b", r"errno.ENOSYS"),
    (r"\bENOTEMPTY\b", r"errno.ENOTEMPTY"),
    (r"\bELOOP\b", r"errno.ELOOP"),
    (r"\bEWOULDBLOCK\b", r"errno.EWOULDBLOCK"),
    (r"\bENOMSG\b", r"errno.ENOMSG"),
    (r"\bEIDRM\b", r"errno.EIDRM"),
    (r"\bECHRNG\b", r"errno.ECHRNG"),
    (r"\bEL2NSYNC\b", r"errno.EL2NSYNC"),
    (r"\bEL3HLT\b", r"errno.EL3HLT"),
    (r"\bEL3RST\b", r"errno.EL3RST"),
    (r"\bELNRNG\b", r"errno.ELNRNG"),
    (r"\bEUNATCH\b", r"errno.EUNATCH"),
    (r"\bENOCSI\b", r"errno.ENOCSI"),
    (r"\bEL2HLT\b", r"errno.EL2HLT"),
    (r"\bEBADE\b", r"errno.EBADE"),
    (r"\bEBADR\b", r"errno.EBADR"),
    (r"\bEXFULL\b", r"errno.EXFULL"),
    (r"\bENOANO\b", r"errno.ENOANO"),
    (r"\bEBADRQC\b", r"errno.EBADRQC"),
    (r"\bEBADSLT\b", r"errno.EBADSLT"),
    (r"\bEDEADLOCK\b", r"errno.EDEADLOCK"),
    (r"\bEBFONT\b", r"errno.EBFONT"),
    (r"\bENOSTR\b", r"errno.ENOSTR"),
    (r"\bENODATA\b", r"errno.ENODATA"),
    (r"\bETIME\b", r"errno.ETIME"),
    (r"\bENOSR\b", r"errno.ENOSR"),
    (r"\bENONET\b", r"errno.ENONET"),
    (r"\bENOPKG\b", r"errno.ENOPKG"),
    (r"\bEREMOTE\b", r"errno.EREMOTE"),
    (r"\bENOLINK\b", r"errno.ENOLINK"),
    (r"\bEADV\b", r"errno.EADV"),
    (r"\bESRMNT\b", r"errno.ESRMNT"),
    (r"\bECOMM\b", r"errno.ECOMM"),
    (r"\bEPROTO\b", r"errno.EPROTO"),
    (r"\bEMULTIHOP\b", r"errno.EMULTIHOP"),
    (r"\bEDOTDOT\b", r"errno.EDOTDOT"),
    (r"\bEBADMSG\b", r"errno.EBADMSG"),
    (r"\bEOVERFLOW\b", r"errno.EOVERFLOW"),
    (r"\bENOTUNIQ\b", r"errno.ENOTUNIQ"),
    (r"\bEBADFD\b", r"errno.EBADFD"),
    (r"\bEREMCHG\b", r"errno.EREMCHG"),
    (r"\bELIBACC\b", r"errno.ELIBACC"),
    (r"\bELIBBAD\b", r"errno.ELIBBAD"),
    (r"\bELIBSCN\b", r"errno.ELIBSCN"),
    (r"\bELIBMAX\b", r"errno.ELIBMAX"),
    (r"\bELIBEXEC\b", r"errno.ELIBEXEC"),
    (r"\bEILSEQ\b", r"errno.EILSEQ"),
    (r"\bERESTART\b", r"errno.ERESTART"),
    (r"\bESTRPIPE\b", r"errno.ESTRPIPE"),
    (r"\bEUSERS\b", r"errno.EUSERS"),
    (r"\bENOTSOCK\b", r"errno.ENOTSOCK"),
    (r"\bEDESTADDRREQ\b", r"errno.EDESTADDRREQ"),
    (r"\bEMSGSIZE\b", r"errno.EMSGSIZE"),
    (r"\bEPROTOTYPE\b", r"errno.EPROTOTYPE"),
    (r"\bENOPROTOOPT\b", r"errno.ENOPROTOOPT"),
    (r"\bEPROTONOSUPPORT\b", r"errno.EPROTONOSUPPORT"),
    (r"\bESOCKTNOSUPPORT\b", r"errno.ESOCKTNOSUPPORT"),
    (r"\bEOPNOTSUPP\b", r"errno.EOPNOTSUPP"),
    (r"\bEPFNOSUPPORT\b", r"errno.EPFNOSUPPORT"),
    (r"\bEAFNOSUPPORT\b", r"errno.EAFNOSUPPORT"),
    (r"\bEADDRINUSE\b", r"errno.EADDRINUSE"),
    (r"\bEADDRNOTAVAIL\b", r"errno.EADDRNOTAVAIL"),
    (r"\bENETDOWN\b", r"errno.ENETDOWN"),
    (r"\bENETUNREACH\b", r"errno.ENETUNREACH"),
    (r"\bENETRESET\b", r"errno.ENETRESET"),
    (r"\bECONNABORTED\b", r"errno.ECONNABORTED"),
    (r"\bECONNRESET\b", r"errno.ECONNRESET"),
    (r"\bENOBUFS\b", r"errno.ENOBUFS"),
    (r"\bEISCONN\b", r"errno.EISCONN"),
    (r"\bENOTCONN\b", r"errno.ENOTCONN"),
    (r"\bESHUTDOWN\b", r"errno.ESHUTDOWN"),
    (r"\bETOOMANYREFS\b", r"errno.ETOOMANYREFS"),
    (r"\bETIMEDOUT\b", r"errno.ETIMEDOUT"),
    (r"\bECONNREFUSED\b", r"errno.ECONNREFUSED"),
    (r"\bEHOSTDOWN\b", r"errno.EHOSTDOWN"),
    (r"\bEHOSTUNREACH\b", r"errno.EHOSTUNREACH"),
    (r"\bEALREADY\b", r"errno.EALREADY"),
    (r"\bEINPROGRESS\b", r"errno.EINPROGRESS"),
    (r"\bESTALE\b", r"errno.ESTALE"),
    (r"\bEUCLEAN\b", r"errno.EUCLEAN"),
    (r"\bENOTNAM\b", r"errno.ENOTNAM"),
    (r"\bENAVAIL\b", r"errno.ENAVAIL"),
    (r"\bEISNAM\b", r"errno.EISNAM"),
    (r"\bEREMOTEIO\b", r"errno.EREMOTEIO"),
    (r"\bEDQUOT\b", r"errno.EDQUOT"),
    # Python fcntl library
    (r"\bfcntl\(", r"fcntl.fcntl("),
    (r"\bflock\(", r"fcntl.lockf("),
    (r"\blockf\(", r"fcntl.lockf("),
    (r"\bLOCK_UN\b", r"fcntl.LOCK_UN"),
    (r"\bLOCK_EX\b", r"fcntl.LOCK_EX"),
    (r"\bLOCK_SH\b", r"fcntl.LOCK_SH"),
    (r"\bLOCK_NB\b", r"fcntl.LOCK_NB"),
    # Python getpass library
    (r"\bgetpass\(", r"getpass.getpass("),
    # Python glob library
    (r"\bglob\(", r"glob.glob("),	# Calling conventions differ
    # Python grp library
    (r"\bgetgrgid\(", r"grp.getgrgid("),
    (r"\bgetgrnam\(", r"grp.getgrnam("),
    # Python math library
    (r"\bacos\(", r"math.acos("),
    (r"\basin\(", r"math.asin("),
    (r"\batan\(", r"math.atan("),
    (r"\batan2\(", r"math.atan2("),
    (r"\bceil\(", r"math.ceil("),
    (r"\bcos\(", r"math.cos("),
    (r"\bcosh\(", r"math.cosh("),
    (r"\bexp\(", r"math.exp("),
    (r"\bfabs\(", r"math.fabs("),
    (r"\bfloor\(", r"math.floor("),
    (r"\bfmod\(", r"math.fmod("),
    (r"\bfrexp\(", r"math.frexp("),	# Calling conventions differ
    (r"\bldexp\(", r"math.ldexp("),
    (r"\blog10\(", r"math.log10("),
    (r"\blog\(", r"math.log("),
    (r"\bmodf\(", r"math.modf("),	# Calling conventions differ
    (r"\bpow\(", r"math.pow("),
    (r"\bsinh\(", r"math.sinh("),
    (r"\bsin\(", r"math.sin("),
    (r"\bsqrt\(", r"math.sqrt("),
    (r"\btan\(", r"math.tan("),
    (r"\btanh\(", r"math.tanh("),
    # Python os library
    (r"\babort\(", r"os.abort("),
    (r"\baccess\(", r"os.access("),
    (r"\bchdir\(", r"os.chdir("),
    (r"\bclose\(", r"os.close("),
    (r"\benviron\(", r"os.environ("),
    (r"\bfchdir\(", r"os.fchdir("),
    (r"\bchroot\(", r"os.chroot("),
    (r"\bchmod\(", r"os.chmod("),
    (r"\bchown\(", r"os.chown("),
    (r"\bctermid\(", r"os.ctermid("),
    (r"\bdup\(", r"os.dup("),
    (r"\bdup2\(", r"os.dup2("),
    (r"\bexecl\(", r"os.execl("),
    (r"\bexecle\(", r"os.execle("),
    (r"\bexeclp\(", r"os.execlp("),
    (r"\bexeclpe\(", r"os.execlpe("),
    (r"\bexecv\(", r"os.execv("),
    (r"\bexecve\(", r"os.execve("),
    (r"\bexecvp\(", r"os.execvp("),
    (r"\bexecvpe\(", r"os.execvpe("),
    (r"\b_exit\(", r"os._exit("),
    (r"\bexit\(", r"os.exit("),
    (r"\bfdopen\(", r"os.fdopen("),
    (r"\bfork\(", r"os.fork("),
    (r"\bfsync\(", r"os.fsync("),
    (r"\bftruncate\(", r"os.ftruncate("),
    (r"\bgetcwd\(", r"os.getcwd("),
    (r"\bgetegid\(", r"os.getegid("),
    (r"\bgeteuid\(", r"os.geteuid("),
    (r"\bgetenv\(", r"os.getenv("),
    (r"\bgetgid\(", r"os.getgid("),
    (r"\bgetgroups\(", r"os.getgroups("),
    (r"\bgetlogin\(", r"os.getlogin("),
    (r"\bgetpgid\(", r"os.getpgid("),
    (r"\bgetpgrp\(", r"os.getpgrp("),
    (r"\bgetpid\(", r"os.getpid("),
    (r"\bgetppid\(", r"os.getppid("),
    (r"\bgetuid\(", r"os.getuid("),
    (r"\bkill\(", r"os.kill("),
    (r"\bkillpg\(", r"os.killpg("),
    (r"\bisatty\(", r"os.isatty("),
    (r"\blseek\(", r"os.lseek("),
    (r"\blchown\(", r"os.lchown("),
    (r"\bgetcwd\(", r"os.getcwd("),
    (r"\blstat\(", r"os.lstat("),
    (r"\bmkfifo\(", r"os.mkfifo("),
    (r"\bmknod\(", r"os.mknod("),
    (r"\bmkdir\(", r"os.mkdir("),
    (r"\bnice\(", r"os.nice("),
    (r"\bopen\(", r"os.open("),
    (r"\bpathconf\(", r"os.pathconf("),
    (r"\bpipe\(", r"os.pipe("),
    (r"\bplock\(", r"os.plock("),
    (r"\bputenv\(", r"os.putenv("),
    (r"\bread\(", r"os.read("),
    (r"\brmdir\(", r"os.rmdir("),
    (r"\bsetegid\(", r"os.setegid("),
    (r"\bseteuid\(", r"os.seteuid("),
    (r"\bsetgid\(", r"os.setgid("),
    (r"\bsetgroups\(", r"os.setgroups("),
    (r"\bsetpgrp\(", r"os.setpgrp("),
    (r"\bsetpgid\(", r"os.setpgid("),
    (r"\bsetreuid\(", r"os.setreuid("),
    (r"\bsetregid\(", r"os.setregid("),
    (r"\bsetsid\(", r"os.setsid("),
    (r"\bsetuid\(", r"os.setuid("),
    (r"\bstrerror\(", r"os.strerror("),
    (r"\bumask\(", r"os.umask("),
    (r"\bsymlink\(", r"os.symlink("),
    (r"\bsystem\(", r"os.system("),
    (r"\btcgetpgrp\(", r"os.tcgetpgrp("),
    (r"\btcsetpgrp\(", r"os.tcsetpgrp("),
    (r"\btmpfile\(", r"os.tmpfile("),
    (r"\bttyname\(", r"os.ttyname("),
    (r"\bunlink\(", r"os.unlink("),
    (r"\bwrite\(", r"os.write("),
    (r"\bwait\(", r"os.wait("),
    (r"\bwaitpid\(", r"os.waitpid("),
    (r"\bWNOHANG\b", r"os.WNOHANG"),
    (r"\bWCONTINUED\b", r"os.WCONTINUED"),
    (r"\bWUNTRACED\b", r"os.WUNTRACED"),
    (r"\bWCOREDUMP\b", r"os.WCOREDUMP"),
    (r"\bWIFCONTINUED\b", r"os.WIFCONTINUED"),
    (r"\bWIFSTOPPED\b", r"os.WIFSTOPPED"),
    (r"\bWIFSIGNALED\b", r"os.WIFSIGNALED"),
    (r"\bWIFEXITED\b", r"os.WIFEXITED"),
    (r"\bWEXITSTATUS\b", r"os.WEXITSTATUS"),
    (r"\bWSTOPSIG\b", r"os.WSTOPSIG"),
    (r"\bWTERMSIG\b", r"os.WTERMSIG"),
    (r"\bO_RDONLY\b", r"os.O_RDONLY"),
    (r"\bO_WRONLY\b", r"os.O_WRONLY"),
    (r"\bO_RDWR\b", r"os.O_RDWR"),
    (r"\bO_NDELAY\b", r"os.O_NDELAY"),
    (r"\bO_NONBLOCK\b", r"os.O_NONBLOCK"),
    (r"\bO_APPEND\b", r"os.O_APPEND"),
    (r"\bO_DSYNC\b", r"os.O_DSYNC"),
    (r"\bO_RSYNC\b", r"os.O_RSYNC"),
    (r"\bO_SYNC\b", r"os.O_SYNC"),
    (r"\bO_NOCTTY\b", r"os.O_NOCTTY"),
    (r"\bO_CREAT\b", r"os.O_CREAT"),
    (r"\bO_EXCL\b", r"os.O_EXCL"),
    (r"\bO_TRUNC\b", r"os.O_TRUNC"),
    (r"\bF_OK\b", r"os.F_OK"),
    (r"\bR_OK\b", r"os.R_OK"),
    (r"\bW_OK\b", r"os.W_OK"),
    (r"\bX_OK\b", r"os.X_OK"),
    (r"\bS_ISUID\b", r"os.S_ISUID"),
    (r"\bS+ISGID\b", r"os.S+ISGID"),
    (r"\bS_ENFMT\b", r"os.S_ENFMT"),
    (r"\bS_ISVTX\b", r"os.S_ISVTX"),
    (r"\bS_IREAD\b", r"os.S_IREAD"),
    (r"\bS_IWRITE\b", r"os.S_IWRITE"),
    (r"\bS_IEXEC\b", r"os.S_IEXEC"),
    (r"\bS_IRWXU\b", r"os.S_IRWXU"),
    (r"\bS_IRUSR\b", r"os.S_IRUSR"),
    (r"\bS_IXUSR\b", r"os.S_IXUSR"),
    (r"\bS_IRWXG\b", r"os.S_IRWXG"),
    (r"\bS_IRGRP\b", r"os.S_IRGRP"),
    (r"\bS_IWGRP\b", r"os.S_IWGRP"),
    (r"\bS_IXGRP\b", r"os.S_IXGRP"),
    (r"\bS_IRWXO\b", r"os.S_IRWXO"),
    (r"\bS_IROTH\b", r"os.S_IROTH"),
    (r"\bS_IWOTH\b", r"os.S_IWOTH"),
    (r"\bS_IXOTH\b", r"os.S_IXOTH"),
    # Python random library -- alas, C rand() doesn't map cleanly
    (r"\bsrand48\(", r"random.seed("),
    (r"\bsrand\(", r"random.seed("),
    # Python os.path library
    (r"\bbasename\(", r"os.path.basename("),
    (r"\bdirname\(", r"os.path.dirname("),
    # Python pwd library
    (r"\bgetpwuid\(", r"pwd.getpwuid("),
    (r"\bgetpwnam\(", r"pwd.getpwnam("),
    # Python string library
    (r"\btoupper\(", r"string.upper("),
    (r"\btolower\(", r"string.lower("),
    # Python sys library
    (r"\bargv\(", r"sys.argv("),
    (r"\bstdin\(", r"sys.stdin("),
    (r"\bstdout\(", r"sys.stdout("),
    (r"\bstderr\(", r"sys.stderr("),
    # Python termios library
    (r"\btcgetattr\(", r"termios.tcgetattr("),		# Calling conventions differ
    (r"\btcsetattr\(", r"termios.tcsetattr("),		# Calling conventions differ
    (r"\btcsendbreak\(", r"termios.tcsendbreak("),
    (r"\btcflush\(", r"termios.tcflush("),
    (r"\btcdrain\(", r"termios.tcdrain("),
    (r"\btcflow\(", r"termios.tcflow("),
    (r"\bVMIN\b", r"termios.VMIN"),
    (r"\bVMAX\b", r"termios.VMAX"),
    (r"\bTCSANOW\b", r"termios.TCSANOW"),
    (r"\bTCSADRAIN\b", r"termios.TCSADRAIN"),
    (r"\bTCSAFLUSH\b", r"termios.TCSAFLUSH"),
    (r"\bTCIFLUSH\b", r"termios.TCIFLUSH"),
    (r"\bTCOFLUSH\b", r"termios.TCOFLUSH"),
    (r"\bTCOOFF\b", r"termios.TCOOFF"),
    (r"\bTCOON\b", r"termios.TCOON"),
)

falsefriends = (
    "frexp", r"getsyx", r"getmaxyx", r"glob", r"ioctl", r"modf",
    "tcgetattr", r"tcsetattr",
    )

# These have to be applied to the entire file without breaking it into regions
file_transformations = (
    # Simple initializers to tuples
    (r"(?:static)?\s+(?:%(type)s|%(class)s)\s+(%(id)s)\[[a-zA-Z0-9._]*]\s*=\s*{([^}]+)}",
     r"\1 = (\2)"),
    (r"enum\s+(%(id)s\s*){\s*",  r"enum \1{\n"),
    (r"enum\s+{\s*",  r"enum {\n"),
    (r"%(ind)s#\s*\$ctopy.*", r""),	# Make hints go away
    (r"(?:int )?main\(int\s+argc,\s+char\s+\*argv\)\s*{",
     "if __name__ == '__main__':"),
    )

# These need to be applied repeatedly within regions.
# They rely on semicolons as statatement end markers.
repeat_transformations = (
    (
    # Group 1: What we're doing here is stripping out prefix, suffix,
    # and wrapper parts of declarations in order to reduce everything
    # to base type followed by whitespace followed by id.  This is
    # significant for simplifying both function formal parameter lists
    # and variable declaration lines.  We'll get rid of the remaining
    # type stuff in a later pass.
    (r"(%(type)s|%(class)s)\s*\*", r"\1 "),	# Pointer type decls
    (r"(%(type)s|%(class)s)(.*), \*", r"\1\2, "),	# Pointer type decls
    (r"(%(type)s|%(class)s)\s*\((%(id)s)\)\(\)", r"\1 \2"),	# Function pointer wrappers
    (r"(%(type)s|%(class)s)\s*(%(id)s)\[\]", r"\1 \2"),	# Array declarators
    ),
    (
    # Group 2: Translate function headers.  This needs to happen after
    # reduction to base types (just above) but before scalar types
    # have been removed entirely.
    (r"\n(?:static\s+)?(?:%(type)s|%(class)s) +(.*\)) *\n", r"\ndef \1:\n"),
    ),
    (
    # Group 3: What we're doing here is trying to get rid of variable
    # declarations that don't have initializer parts.
    # Scalar-vars just after the type and before a comma go away.
    (r"(\n[ \t]*(?:%(type)s))(\s*%(id)s),", r"\1 "),
    # Scalar-vars just after type and before a semi go away, but semi stays.
    (r"(\n[ \t]*(?:%(type)s))(\s*%(id)s);", r"\1;"),
    # Class-vars after class names and before comma or semi get an initializer.
    (r"(\n[ \t]*)(%(class)s)(\s*%(id)s)([;,])", r"\1\2\3 = \2()\4"),
    # Scalar-vars between a comma and a trailing semicolon go away.
    (r"(\n[ \t]*)((?:%(type)s).*)(,\s*%(id)s\s*);", r"\1\2;"),
    # Class-Vars between comma and semicolon get a following initializer 
    (r"(\n[ \t]*)(%(class)s)(.*,\s)*(%(id)s)(\s*;)", r"\1\2\3\4 = \2()\5"),
    # Scalar-vars between commas in a declaration line go away.
    (r"(\n[ \t]*(?:%(type)s)\s+.*)(,\s*%(id)s)(,.*);", r"\1\3;"),
    # Bare class-vars between commas get an initializer
    (r"(\n[ \t]*)(%(class)s)(\s+.*,)(\s*%(id)s),(.*);",r"\1\2\3\4 = \2(),\5;"),
    # Any declaration line not containing an initializer goes away.
    (r"\n[ \t]*(?:%(type)s|%(class)s)[^=;]*;", r""),
    ),
    (
    # Group 4: At this point all declarations left have initializers.
    # Replace commas in declaration lines with semis, otherwise Python will
    # barf later because it thinks that, e.g., a=4, b=5  is an attempt to
    # assign a constant to a tuple.
    # FIXME: This will fail messily on GCC structure intializers.
    (r"(\n[ \t]*(?:%(type)s|%(class)s).*),(.*);", r"\1;\2"),
    ),
    (
    # Group 5: Now rip out all remaining base type information.
    # This will strip remaining type declarators out of formal parameter lists.
    # It will also remove types from the beginning of declaration lines.
    # Won't nuke casts because it looks for at least one following whitespace.
    (r"(?:%(type)s|%(class)s)[\s;]\s*", r""),
    ),
)

# These get applied once within regions, before type info has been stripped
pre_transformations = (
    # We used to do function header translation here.   We leave
   # this in place because we'll probably need to do things here again.
    )

# These get applied once within regions, after type info has been stripped
post_transformations = (
    # some consequences of having translated function headers
    (r"\(void\):\n", r"():\n"),
    (r"def(.*):\n\Z", r"def\1:\n    "),	# indent comment on line after def
    # externs can just disappear -- this may discard a following comment
    (r"extern[^;]+;.*\n", r""),
    # macros
    (r"#define\s+(%(id)s)\s+(.*)", r"\1\t= \2"),
    (r"#define\s+(%(id)s)\(([^)]*)\)\s+(.*\))", r"def \1(\2):\treturn \3"),
    (r"#define\s+(%(id)s)\(([^)]*)\)\s+([^(].*)", r"def \1(\2):\t\3"),
    # control structure
    (r"\bif *\((.*)\)(\s*{)?", r"if \1:"),
    (r"\bwhile *\((.*)\)(\s*{)?", r"while \1:"), 
    (r"\bwhile 1:", r"while True:"),
    (r"\bfor \(;;\)(\s*{)?", r"while True:"),
    (r"\bfor \((%(id)s) *= *0; *\1 *<= *([^;]+); *\1\+\+\)(\s*{)?",
     					r"for \1 in range(\2+1):"),
    (r"\bfor \((%(id)s) *= *([^;]+); *\1 *<= *([^;]+); *\1\+\+\)(\s*{)?",
     					r"for \1 in range(\2, \3+1):"),
    (r"\bfor \((%(id)s) *= *0; *\1 *< *([^;]+); *\1\+\+\)\s*{",
     					r"for \1 in range(\2):"),
    (r"\bfor \((%(id)s) *= *([^;]+); *\1 *< *([^;]+); *\1\+\+\)(\s*{)?",
     					r"for \1 in range(\2, \3):"),
    (r"else if", r"elif"),
    (r"(?:} )?else\s*{", r"else"),
    (r"(?<!#)else", r"else:"),
    (r"\bdo\s*{", r"while True:"),
    (r"}\s*while\s*(\(.*\));", r"if not \1: break	# DO-WHILE TERMINATOR -- INDENTATION IS PROBABLY WRONG"), 
    (r"switch *\((.*)\)(\s*{)?", r"switch \1:"),# Not Python, but less ugly
    # constants
    (r"\btrue\b", r"True"),	# C99
    (r"\bfalse\b", r"False"),	# C99
    (r"\bTRUE\b", r"True"),	# pre-C99
    (r"\bFALSE\b", r"False"),	# pre-C99
    # expression operations
    (r" *\&\& *", r" and "),
    (r" *\|\| *", r" or "),
    (r"-\>", r"."),
    (r"!(?!=) *", r"not "),
    (r"(and|or) *\n", r"\1 \\\n"),
    # most common uses of address operator
    (r"return *&", r"return "),
    (r"= *&", r"= "),
    # increment and decrement statements
    (r"(%(id)s)\+\+([;\n])", r"\1 += 1\2"),
    (r"(%(id)s)--([;\n])", r"\1 -= 1\2"),
    (r"\+\+(%(id)s)([;\n])", r"\1 += 1\2"),
    (r"--(%(id)s)([;\n])", r"\1 -= 1\2"),
    # no-op voids
    (r"\n[ \t]*\(void\)", r"\n"),  
    # C functions that turn into Python builtins
    (r"\batoi\(", r"int("),
    (r"\batof\(", r"float("),
    (r"\batol\(", r"long("),
    (r"\bfopen\(", r"open("),
    (r"\bputchar\(", r"stdout.write("),
    (r"\bgetchar\(\)", r"stdout.read(1)"),
    (r"\bstrlen\(", r"len("),
    (r"\bstrcmp\((%(exp)s),\s*(%(exp)s)\)\s*==\s*0", r"\1 == \2"),
    (r"\bstrcmp\((%(exp)s),\s*(%(exp)s)\)\s*!=\s*0", r"\1 != \2"),
    (r"\bstrcpy\((%(exp)s),\s*(%(exp)s)\)", r"\1 = \2"),
    # Python time library
    (r"\btime\(NULL\)", r"time.time()"),
    # well-known includes
    (r"#include \<string.h\>\n", r""),
    (r"#include \<stdlib.h\>\n", r""),
    (r"#include \<stdbool.h\>\n", r""),
    (r"#include \<stdio.h\>\n", r"import sys\n"),
    (r"#include \<math.h\>\n", r"import math\n"),
    (r"#include \<time.h\>\n", r"import time\n"),
    (r"#include \<regex.h\>\n", r"import re\n"),
    (r"#include \<curses.h\>\n", r"import curses\n"),
    (r"#include \<termios.h\>\n", r"import termios\n"),
)

final_transformations = (
    # block delimiters -- do these as late as possible, they're useful
    (r";(%(eol)s)", r"\1"),
    (r"\n[ \t]*}%(eol)s", r""),
    (r"(?<!=\n)\n{\n", r"\n"),	# Start-of-line brace that's not an initializer
    (r"%% \(,(%(ind)s)", r"%\1("),
    )

def single_apply(transforms, text):
    "Apply specified set of transformations once."
    for (fro, to) in transforms:
        oldtext = text
        # Prepending \n then stripping it means that \n can reliably
        # be used to recognize start of line.
        text = re.sub(fro % shorthands, to, "\n" + oldtext)[1:]
        if debug >= 2 and text != oldtext:
            print "%s transforms '%s' to '%s'" % ((fro, to), `oldtext`, `text`)
    return text

def repeat_apply(transforms, text):
    "Repeatedly apply specified transformations to text until it's stable."
    while True:
        transformed = single_apply(transforms, text)
        if transformed != text:
            text = transformed
        else:
            break
    return text

def ctopy(input):
    "Transform C to Python."
    if debug >= 2:
        print "Gathering hints"
    hints = re.finditer(r"\$ctopy (.*)", input)
    for hint in hints:
        process_hint(hint.group(1))
    if debug >= 2:
        print "Processing inline enums"
    global stringify
    enums = re.finditer(r"enum[ \t]*{(.*)} (%(id)s)" % shorthands, input)
    for instance in enums:
        stringify += instance.group(1).replace(" ", "").split(",")
        input = input[:instance.start(0)] + input[instance.start(2):]
    if debug:
        print "Pre-transformations begin"
    input = repeat_apply(file_transformations, input)
    if debug >= 2:
        print "After pre-transformations: %s" % `code`
    if debug:
        print "Region analysis begins"
    boundaries = [0]
    state = "text"
    for i in range(len(input)):
        if state == "text":
            if input[i] == '"' and (i == 0 or input[i-1] != '\\'):
                if debug >= 2:
                    print "String literal starts at %d" % i
                boundaries.append(i)
                state = "stringliteral"
            elif input[i:i+2] == "/*":
                if debug >= 2:
                    print "Closed comment starts at %d" % (i-1)
                boundaries.append(i)
                state = "closedcomment"
            elif input[i:i+2] == "//":
                if debug >= 2:
                    print "Open comment starts at %d" % i
                boundaries.append(i)
                state = "opencomment"
            elif input[i:].startswith("typedef enum {") or input[i:].startswith("enum {"):
                if debug >= 2:
                    print "enumeration starts at %d" % i
                if input[i-2:i+1] != 'f e':
                    boundaries.append(i)
                boundaries.append(i + input[i:].find("enum") + 5)
            elif input[i:].startswith("\n}"):
                if debug >= 2:
                    print "start-of-line brace at %d" % i
                boundaries.append(i)
                boundaries.append(i+2)
        elif state == "stringliteral":
            if input[i] == '"' and (i == 0 or input[i-1] != '\\'):
                if debug >= 2:
                    print "String ends at %d" % i
                boundaries.append(i+1)
                state = "text"
        elif state == "closedcomment":
            if input[i:i+2] == "*/":
                if debug >= 2:
                    print "closed comment ends at %d" % (i+1)
                boundaries.append(i+2)
                state = "text"                
        elif state == "opencomment":
            if input[i] == "\n":
                if debug >= 2:
                    print "Open comment ends at %d" % (i+1)
                boundaries.append(i+1)
                state = "text"
    boundaries.append(len(input))
    if debug >= 2:
        print "Boundaries:", boundaries
    regions = []
    for i in range(len(boundaries)-1):
        regions.append(input[boundaries[i]:boundaries[i+1]])
    regions = filter(lambda x: x != '', regions)
    if debug:
        print "Regexp transformation begins"
    if debug:
        import pprint
        pp = pprint.PrettyPrinter(indent=4)
        print "Regions:"
        pp.pprint(regions)
    if debug >= 2:
        print "Processing printf-like functions"
    for (i, here) in enumerate(regions):
        if regions[i][0] != '"' or not "%" in here:
            continue
        else:
            for func in printflike:
                if re.search(r"\b%s\([^;]*\Z" % func, regions[i]):
                    break
                else:
                    continue	# Didn't find printf-like function
        # Found printf-like function.  Replace first comma in the
        # argument region with " % (".  This copes gracefully with the
        # case where the format string is wrapped in _( ) for
        # initialization.
        regions[i+1] = re.sub(r",\s*", r" % (", regions[i+1], 1)
        j = regions[i+1].find("%") + 2
        parenlevel = 0
        while j < len(regions[i+1]):
            if regions[i+1][j] == "(":
                parenlevel += 1
            if regions[i+1][j] == ")":
                parenlevel -= 1
            if parenlevel == 0:
                regions[i+1] = regions[i+1][:j] + ")" + regions[i+1][j:]
                break
            j += 1
    importlist = []
    try:
        for i in range(len(regions)):
            if regions[i][:2] == "/*":
                if regions[i].count("\n") <= 1:		# winged comment
                    regions[i] = "#" + regions[i][2:-2]
                elif re.search("/\*+\n", regions[i]):	# boxed comment
                    regions[i] = re.sub(r"\n([ \t]*) \* ?", r"\n\1",regions[i])
                    regions[i] = re.sub(r"\n([ \t]*)\*", r"\n\1", regions[i])
                    regions[i] = re.sub(r"^([ \t]*)/\*+\n", r"\1#\n", regions[i])
                    regions[i] = re.sub(r"\n([ \t]*)\**/", r"\n\1", regions[i])
                    regions[i] = re.sub(r"\n([ \t]*)(?!#)", r"\n\1# ", regions[i])
                else:
                    regions[i] = regions[i].replace("/*", "#")
                    regions[i] = regions[i].replace("\n*/", "\n#")
                    regions[i] = regions[i].replace("*/", "")
                    regions[i] = regions[i].replace("\n *", "\n")
                    regions[i] = regions[i].replace("\n", "\n#")
            elif regions[i][:2] == "//":
                regions[i] = "#" + regions[i][2:]
            elif regions[i][0] != '"':
                if debug >= 2:
                    print "Doing pre transformations"
                regions[i] = single_apply(pre_transformations, regions[i])
                if debug >= 2:
                    print "Doing repeated transformations"
                for (j, hack) in enumerate(repeat_transformations):
                    if debug >= 2:
                        print "Repeat transformations group %d" % (j+1)
                    regions[i] = repeat_apply(hack, regions[i])
                if debug:
                    print "Function and method mappings begin"
                for (fro, to, module) in funmappings:
                    if re.search(fro, regions[i]):
                        regions[i] = re.sub(fro, to, regions[i])
                        if module not in importlist and module:
                            importlist.append(module)
                for name in falsefriends:
                    if re.search(r"\b" + name + r"\b\(", regions[i]):
                        sys.stderr.write("warning: %s calling conventions differ between C and Python." % name)
                if debug >= 2:
                    print "Doing post transformations"
                regions[i] = single_apply(post_transformations, regions[i])
                for str in stringify:
                    regions[i] = re.sub(r"\b" + str + r"\b",
                                        '"' + str + '"', regions[i])
    except IndexError:
        sys.stderr.write("ctopy: pathological string literal at %d.\n" % boundaries[i])
        raise SystemExit, 1
    if debug:
        "Enumeration processing"
    state = "plain"
    for (i, region) in enumerate(regions):
        # first compute a parse state
        if region.startswith("typedef enum"):
            state = "typedef"
        elif region.startswith("enum"):
            state = "enum"
        elif region == "\n}":
            if state in ("typedef", "enum"):
                regions[i] = ''
                state = "plain"
        # now do something useful with it
        if debug >= 3:
            print "Enumeration processing: state = %s, region = %s" % (state, `regions[i]`)
        if state in ("enum", "typedef"):
            if regions[i] == "enum ":
                m = re.match("(%(id)s) {" % shorthands, regions[i+1])
                if m:
                    shorthands['type'] += "|" + m.group(1)
                    regions[i] = '# From enumerated type \'%s\'\n' % m.group(1)
                    regions[i+1] = regions[i+1][m.end(0)+1:]
                else: 
                    regions[i] = '# From anonymous enumerated type\n'
            elif regions[i] == "typedef enum ":
                m = re.match("\s* (%(id)s)\s*;?" % shorthands, regions[i+3])
                if m:
                    shorthands['type'] += "|" + m.group(1)
                    regions[i] = '# From enumerated type \'%s\'\n' % m.group(1)
                    regions[i+3] = regions[i+3][:m.start(0)] + "\n\n"
                else: 
                    regions[i] = '# From anonymous typedefed enum (?!)\n'
            else:
                regions[i] = re.sub(",\s*", "\n", regions[i])
                val = 0
                txt = regions[i].split("\n")
                for j in range(len(txt)):
                    if txt[j] == '' or txt[j].startswith("{"):
                        pass
                    elif '=' not in txt[j]:
                        txt[j] += " = %d" % val
                        val += 1
                regions[i] = "\n".join(txt)
    if debug:
        "Final transformations begin"
    regions = map(lambda r: repeat_apply(final_transformations, r),regions)
    text = "".join(regions)
    if importlist:
        importlist = "import " + ", ".join(importlist) + "\n"
        text = importlist + text
    # Emit what we got.  Preserve imports in case this is a .h file 
    return text

def process_hint(line):
    "Process a translation-hints line."
    if line[0] == "#":
        pass
    else:
        global stringify, printflike
        if debug >= 2:
            print "Hint: %s" % `line`
        lst = line.replace(",", " ").split()
        if lst[0] == "stringify":
            stringify += lst[1:]
        elif lst[0] == "type":
            for tok in lst[1:]:
                shorthands["type"] += r"|\b" + tok + r"\b" 
        elif lst[0] == "class":
            for tok in lst[1:]:
                shorthands["class"] += r"|\b" + tok + r"\b"
        elif lst[0] == "printflike":
            printflike += lst[1:]

if __name__ == "__main__":
    import getopt
    (options, arguments) = getopt.getopt(sys.argv[1:], "c:h:ds:t:")
    debug = 0;
    for (switch, val) in options:
	if (switch == '-c'):
            shorthands["class"] += r"|\b" + val + r"\b"
	elif (switch == '-d'):
	    debug += 1
	elif (switch == '-h'):
            for line in open(val):
                process_hint(line)
	elif (switch == '-s'):
            stringify.append(val)
	elif (switch == '-t'):
            shorthands["type"] += r"|\b" + val + r"\b" 

    code = sys.stdin.read()
    if debug >= 2:
        print "Input is: %s" % `code`
    text = ctopy(code)
    if debug:
        print "Output:"
    sys.stdout.write(text)
